//! # kore
//!
//! Convert JSON values into **`.kore`** — a compact, human-readable text
//! format for representing API responses and structured data — without
//! losing any information from the original JSON.
//!
//! This is a Rust port of the [`kore-js`](https://github.com/kore-lang/kore-js)
//! reference implementation, kept output-compatible for the common cases
//! (flat objects, tables, lists, scalars, envelope-style API responses)
//! while fixing a couple of small correctness issues found in the original.
//! See the README's "Differences from kore-js" section for the full list.
//!
//! ## Quick start
//!
//! ```
//! use kore::{to_kore, KoreOptions};
//! use serde_json::json;
//!
//! let hikes = json!([
//!     { "id": 1, "name": "Blue Lake Trail", "km": 7.5, "sunny": true },
//!     { "id": 2, "name": "Ridge Overlook",  "km": 9.2, "sunny": false },
//! ]);
//!
//! let result = to_kore(&hikes, &KoreOptions::new("hikes"));
//! println!("{}", result.kore);
//! ```
//!
//! Output:
//!
//! ```text
//! hikes[id, name, km, sunny]:
//!   1 | Blue Lake Trail | 7.5 | true
//!   2 | Ridge Overlook  | 9.2 | false
//! ```
//!
//! ## Parsing a JSON string directly
//!
//! ```
//! use kore::{to_kore_from_str, KoreOptions};
//!
//! let result = to_kore_from_str(
//!     r#"[{"id":1,"name":"ana"}]"#,
//!     &KoreOptions::new("users"),
//! ).unwrap();
//! assert!(result.kore.contains("users["));
//! ```
//!
//! ## Type inference
//!
//! Setting [`KoreOptions::infer_types`] adds an `@types { ... }` block above
//! a table, inferring a narrow type per column from the data itself:
//!
//! ```
//! use kore::{to_kore, KoreOptions};
//! use serde_json::json;
//!
//! let data = json!([{ "id": 1, "km": 7.5, "active": true }]);
//! let result = to_kore(&data, &KoreOptions::new("items").infer_types(true));
//! assert!(result.kore.contains("@types"));
//! ```

mod converter;
mod infer_types;
mod serialize;
mod types;

pub use infer_types::{build_types_block, infer_table_types, infer_value_type};
pub use serialize::{ctx_value, serialize_value};
pub use types::{CtxValue, KoreOptions, KoreResult, Structure};

use serde_json::Value;

/// Convert a [`serde_json::Value`] into `.kore` text.
///
/// This is the main entry point. It inspects `json` and dispatches to the
/// appropriate renderer:
///
/// - an array of objects becomes a `name[col, col2]:` **table**
/// - an array of primitives becomes a `name: a, b, c` **list**
/// - an object with one scalar-free key becomes a `ctx(...)` **envelope**
///   wrapping whatever that key holds (handy for API responses shaped like
///   `{ "status": "ok", "items": [...] }`)
/// - a plain flat object becomes a compact `name(k=v, k2=v2)` line
/// - anything else becomes a `name: value` **scalar**
///
/// See the crate-level docs for examples of each shape.
pub fn to_kore(json: &Value, opts: &KoreOptions) -> KoreResult {
    let mut parts: Vec<String> = Vec::new();

    if let Some(comment) = &opts.comment {
        parts.push(format!("// {}\n", comment));
    }

    if !opts.ctx.is_empty() {
        let ctx_line = build_ctx_block(opts);
        parts.push(ctx_line.trim().to_string());
        parts.push(String::new());
    }

    let result = converter::convert_any(json, &opts.block_name, opts);
    parts.push(result.kore);

    KoreResult {
        kore: parts.join("\n"),
        ..result
    }
}

fn build_ctx_block(opts: &KoreOptions) -> String {
    let parts: Vec<String> = opts
        .ctx
        .iter()
        .map(|(k, v)| format!("{}={}", k, ctx_value(v)))
        .collect();
    format!("ctx({})\n", parts.join(", "))
}

/// Parse a JSON string and convert it to `.kore` in one step.
///
/// Returns the underlying [`serde_json::Error`] if `json_str` isn't valid
/// JSON.
///
/// ```
/// use kore::{to_kore_from_str, KoreOptions};
///
/// let result = to_kore_from_str(r#"{"name":"ana","km":7.5}"#, &KoreOptions::default())
///     .expect("valid json");
/// assert!(result.kore.contains("name=ana"));
/// ```
pub fn to_kore_from_str(
    json_str: &str,
    opts: &KoreOptions,
) -> Result<KoreResult, serde_json::Error> {
    let parsed: Value = serde_json::from_str(json_str)?;
    Ok(to_kore(&parsed, opts))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn comment_header() {
        let opts = KoreOptions::new("data").comment("generated by kore");
        let r = to_kore(&json!({"x": 1}), &opts);
        assert!(r.kore.starts_with("// generated by kore"));
    }

    #[test]
    fn ctx_option_adds_top_line() {
        let opts = KoreOptions::new("friends")
            .with_ctx("task", "hike planner")
            .with_ctx("ver", 1i32);
        let r = to_kore(&json!(["ana", "luis"]), &opts);
        assert!(r.kore.starts_with("ctx("));
        assert!(r.kore.contains("task="));
        assert!(r.kore.contains("ver=1"));
    }

    #[test]
    fn from_str_parses_then_converts() {
        let r = to_kore_from_str(r#"[{"id":1,"name":"ana"}]"#, &KoreOptions::new("users"))
            .unwrap();
        assert_eq!(r.structure, Structure::Table);
        assert!(r.kore.contains("users["));
    }

    #[test]
    fn from_str_propagates_parse_errors() {
        let err = to_kore_from_str("not json", &KoreOptions::default());
        assert!(err.is_err());
    }
}